### ISSUE TITLE
make: command: Command not found

### ISSUE THREAD

**Issue by Dikaryotic** [bcgsc/LongStitch#13]
Hiya, 

I saw the biorxiv and thought I'd give LongStitch a go with some of my nanopore data. I've installed all the dependencies but when I go to run the program I'm getting the following error:

make: command: Command not found
make: command: Command not found
make: *** No rule to make target 'home/Desktop/Data/assembly.fa.fa', needed by 'home/Desktop/Data/assembly.fa.cut250.tigmint.fa'. stop. 

Thoughts? 

Cheers,
C

**Comment by tbenavi1** [comment]
I also ran into this issue, but resolved it. The first important points are that the draft file must have .fa extension and that the read file must have .fq.gz or .fa.gz extension.

Then, the command to run the default pipeline on a draft assembly draft-assembly.fa with the reads reads.fa.gz and a genome size of gsize is:

longstitch run draft=draft-assembly reads=reads G=gsize

where the ".fa" and ".fa.gz" are not present in the command line. Hope this helps.

**Comment by lcoombe** [comment]
Hi @Dikaryotic and @tbenavi1,

Thank you @tbenavi1 for providing the answer! 
Yes, your `draft` assembly should have a `.fa` extension, and be present in the current working directory, as opposed to providing a full path, as it looks like you have. And also, as @tbenavi1 correctly mentions, the suffix should not be included in the command-line invocation. 

I'm planning on adding a small 'test' which I hope will also help with these sorts of questions.

Thank you for your interest in LongStitch!

Lauren

**Comment by Dikaryotic** [comment]
That worked perfectly, thanks! 

Two follow up things, during the pipeline it errored out due to not having samtools faidx installed. Might want to pop that in as a dependency? 

The pipeline ran through to the ntlink-abyss stage where it exited out at the following. I'm just assuming that's an incomplete run? If not, what's the final assembly? 

"2021-06-22 10:28:14.513155  : Finding optimal n...
2021-06-22 10:28:14.513576  : Optimal n = 9 at N50 = 344752.0
2021-06-22 10:28:14.513597 : Building path graph
Printing paths for optimal N50, no stitching...

2021-06-22 10:28:14.519480 : Finding paths

Total number of components in graph: 308 

MergeContigs -k2 draft.cut250.tigmint.fa out.k32.w100.z1000.stitch.path > draft.cut250.tigmint.fa.k32.w100.z1000.stitch.abyss-scaffold.fa
The minimum coverage of single-end contigs is inf.
The minimum coverage of merged contigs is inf.
rm out.k32.w100.z1000.n*.abyss-scaffold.path out.k32.w100.z1000.n*.abyss-scaffold.path.sterr
ln -sf draft.cut250.tigmint.fa.k32.w100.z1000.stitch.abyss-scaffold.fa draft.cut250.tigmint.fa.k32.w100.z1000.ntLink.scaffolds.fa  "

**Comment by lcoombe** [comment]
Hi @Dikaryotic,

Excellent - I'm glad you got it running ok!

Thanks for the heads up about `samtools faidx` - I will definitely add that as a dependency in the README.

That looks like a complete run to me based on the log (assuming you ran the default `longstitch run`)! You'll see the final line:
```
ln -sf draft.cut250.tigmint.fa.k32.w100.z1000.stitch.abyss-scaffold.fa draft.cut250.tigmint.fa.k32.w100.z1000.ntLink.scaffolds.fa
```
So, your final assembly post Tigmint and ntLink is in `draft.cut250.tigmint.fa.k32.w100.z1000.ntLink.scaffolds.fa`

Is there anything you could suggest to add to the logs that would make it more clear that the run was successful? It's great to have feedback from users for that sort of thing.

Lauren

**Comment by Dikaryotic** [comment]
Hi Lauren, 

Oh! Heh yeah, add something at the end like "run completed successfully, your final assembly is XXX" 

Maybe a little info about what the different run options are about. When would I want to use these for example?
tigmint-ntLink-arks	run full LongStitch pipeline: Tigmint, ntLink, then ARCS in kmer mode
tigmint-ntLink-arcs	run full LongStitch pipeline: Tigmint, ntLink, then ARCS

I ran it with the standard longstitch run. Would I maybe get a better result with one of those? 

Could be worth mentioning that you just want to input the name of the draft and reads as opposed to the full. draft=draft-assembly instead of draft=draft-assembly.fa yah know? That isn't something I've encountered before and I didnt even think to try. 

I think that's everything for now :) The pipeline ran pretty fast for me btw! It's a fungal genome, 33M, some 80X long read coverage. Completed in like 5 minutes on my home machine. 32 Gb ram, 8 core/16 thread Ryzen 7 1800X cpu. 

Cheers,
C

**Comment by lcoombe** [comment]
Great - thanks for the feedback! I'll work on adding some more log messages to the script to make it really clear where the output scaffolds are. I'll also add a bit to the help page and README to hopefully make the invocation clearer.

I'm really glad to hear that the pipeline ran quickly for you! It's really useful for us to hear about user experiences :)

All the best,
Lauren
