### ISSUE TITLE
Longstitch crashes immediately

### ISSUE THREAD

**Issue by charlesfeigin** [bcgsc/LongStitch#16]
Hi,

I am trying to scaffold an assembly using pacbio reads. I did the bioconda install and my command looks like this:

longstitch run t=32 draft=eq_cssABC_fq_flye2.8.3_g3.086Gtresti2 reads=XDOVE_20210_S64049ABC_S64018AB.css G=3000000000

However, the program crashes immediately with the following messages:

tigmint-make tigmint-long draft=eq_cssABC_fq_flye2.8.3_g3.086Gtresti2 reads=XDOVE_20210_S64049ABC_S64018AB.css cut=250 t=32 G=3000000000 span=auto dist=auto
make[1]: Entering directory '/data/cfeigin/assembly'
zsh: no such option: pipefail
zsh: no such option: pipefail
zsh: no such option: pipefail
zsh: no such option: pipefail
sh -c 'gunzip -c XDOVE_20210_S64049ABC_S64018AB.css.fq.gz | \
/tigmint_estimate_dist.py - -n 1000000 -o XDOVE_20210_S64049ABC_S64018AB.css.tigmint-long.params.tsv'
zsh: no such option: pipefail
make[1]: *** [/home/cfeigin/.conda/envs/longstitch_v1.0.1_env/bin/share/tigmint-1.2.4-0/bin/tigmint-make:236: XDOVE_20210_S64049ABC_S64018AB.css.tigmint-long.params.tsv] Error 1
make[1]: Leaving directory '/data/cfeigin/assembly'
make: *** [/home/cfeigin/.conda/envs/longstitch_v1.0.1_env/bin/share/longstitch-1.0.1-0/longstitch:155: eq_cssABC_fq_flye2.8.3_g3.086Gtresti2.cut250.tigmint.fa] Error 2

Do you have any idea of what might be causing this? Thanks!

**Comment by lcoombe** [comment]
Hi @charlesfeigin,

So it looks like it's an issue with the initial `tigmint-long` step in the pipeline - Could you try to `conda install zsh` to see if that fixes it? Which version of `zsh` are you using? (Could do `zsh --version` after the install)
We also have a demo in the `tests` directory which is useful for troubleshooting installations.

Thank you for your interest in LongStitch!
Lauren

**Comment by charlesfeigin** [comment]
Hi Laura,

Thanks so much for your reply. 

My version of zsh is 5.0.2. I'm installing a newer version now.

Overnight I found threads for other programs giving similar errors and was able to get the program to run much farther by commenting out the line "SHELL=zsh -e -o pipefail" in tigmint-make. This run failed with the following:

[M::worker_pipeline::5858.806*22.02] mapped 2015014 sequences
[M::worker_pipeline::5879.341*21.98] mapped 2015217 sequences
[M::worker_pipeline::5904.983*21.96] mapped 1690598 sequences
[M::main] Version: 2.21-r1071
[M::main] CMD: minimap2 -y -t32 -x map-ont --secondary=no eq_cssABC_fq_flye2.8.3_g3.086Gtresti2.fa -
[M::main] Real time: 5905.677 sec; CPU: 129647.242 sec; Peak RSS: 22.665 GB
Warning: malformed fasta index file eq_cssABC_fq_flye2.8.3_g3.086Gtresti2.fa.faidoes not have enough fields @ line 1
contig_1        129844  10      60      61      25427   37896   38218   28303
indexlr v1.3: Using more than 5 threads does not scale, reverting to 5.
[2021-07-07 23:24:40][WARNING] eq_cssABC_fq_flye2.8.3_g3.086Gtresti2.cut250.tigmint.fa is empty.
indexlr v1.3: Using more than 5 threads does not scale, reverting to 5.
Running ntLink stitch paths stage...

2021-07-08 00:25:31.307666  : Finding optimal n...
2021-07-08 00:25:31.308490  : Optimal n = 0 at N50 = 0
2021-07-08 00:25:31.308516 : Building path graph
Traceback (most recent call last):
  File "/home/cfeigin/.conda/envs/longstitch_v1.0.1_env/bin/share/ntlink-1.0.1-0/bin/ntlink_stitch_paths.py", line 520, in <module>
    main()
  File "/home/cfeigin/.conda/envs/longstitch_v1.0.1_env/bin/share/ntlink-1.0.1-0/bin/ntlink_stitch_paths.py", line 516, in main
    NtLinkPath().main()
  File "/home/cfeigin/.conda/envs/longstitch_v1.0.1_env/bin/share/ntlink-1.0.1-0/bin/ntlink_stitch_paths.py", line 464, in main
    path_graph = self.read_paths(best_file)
  File "/home/cfeigin/.conda/envs/longstitch_v1.0.1_env/bin/share/ntlink-1.0.1-0/bin/ntlink_stitch_paths.py", line 80, in read_paths
    with open(path_filename, 'r') as path_file:
TypeError: expected str, bytes or os.PathLike object, not NoneType
make[1]: *** [/home/cfeigin/.conda/envs/longstitch_v1.0.1_env/bin/share/ntlink-1.0.1-0/ntLink:160: out.k32.w100.z1000.stitch.path] Error 1
make[1]: *** Deleting file 'out.k32.w100.z1000.stitch.path'
make: *** [/home/cfeigin/.conda/envs/longstitch_v1.0.1_env/bin/share/longstitch-1.0.1-0/longstitch:165: eq_cssABC_fq_flye2.8.3_g3.086Gtresti2.cut250.tigmint.fa.k32.w100.z1000.stitch.abyss-scaffold.fa] Error 2

I will un-comment the line in tigmint-make for a test run with the newer version of zsh and give that a try. Very excited to get this running :)

**Comment by lcoombe** [comment]
Hi @charlesfeigin,

Sounds good - let me know if the newer `zsh` works! 

It also looks like you have a malformed `fai` file, which may have caused `tigmint-long` to fail?
```
Warning: malformed fasta index file eq_cssABC_fq_flye2.8.3_g3.086Gtresti2.fa.faidoes not have enough fields @ line 1
```
```
[2021-07-07 23:24:40][WARNING] eq_cssABC_fq_flye2.8.3_g3.086Gtresti2.cut250.tigmint.fa is empty.
```
I'd hope that the newer `zsh` will work for you though - I tested with the conda `zsh` just now, and it worked fine for me.  I'd definitely suggest using our `tests` demo script to help you quickly test your installation - it's a very small dataset, so runs extremely quickly. 

Lauren

**Comment by charlesfeigin** [comment]
That's odd about the .fai file, it was made using samtools and I've used it with other tools. I will try having longstitch rebuild it.

I'm sorry if this is a silly question, but do you know where the tests folder would go when installing via conda? I feel like I've looked through every folder in my conda environment and haven't been able to find it. I wasn't able to get it to install via source.

**Comment by lcoombe** [comment]
Hi @charlesfeigin,

Yeah not sure about the `fai` file - could be an error that is in the end related to `zsh`? But yeah worth doing a clean run when the `zsh` is sorted!

That isn't a silly question - I should have been more specific that the `tests` are only on the github repository, not the conda installation (I could add that to the conda formula though if it would be helpful?). You can get that folder by either downloading the release tarball or `git clone`. You don't need to worry about installing via source - you can just use your conda installation and run the shell script.

**Comment by lcoombe** [comment]
```
samtools: error while loading shared libraries: libcrypto.so.1.0.0: cannot open shared object file: No such file or directory
```
It appears that there is something wrong with your samtools installation?

**Comment by charlesfeigin** [comment]
I realized a mistake I had made when getting zsh updated. I had started zsh by mistake but then instead of closing it had opened another bash session in which my environment was no longer active. Apologies, I will backtrack and sort this out.

**Comment by lcoombe** [comment]
> I realized a mistake I had made when getting zsh updated. I had started zsh by mistake but then instead of closing it had opened another bash session in which my environment was no longer active. Apologies, I will backtrack and sort this out.

No worries! Yeah as I mentioned in my last comment - sometimes I find a fresh conda environment is the best way to go. Hopefully that will sort the installation out!

**Comment by charlesfeigin** [comment]
That seems to have been the issue! I was able to get a test to finish and a preliminary rerun on a subset of my own data. Thanks so much for your help!

**Comment by lcoombe** [comment]
Excellent - I'm glad to hear you have it working! 
I'll look at adding `zsh` as a dependency for Tigmint upstream in bioconda - other users may encounter the same error if they have an older `zsh` version on their systems!

**Comment by charlesfeigin** [comment]
Just wanted to say longstitch performed really well! Got awesome results scaffolding HiFi contigs using the longer, higher coverage CLR subreads that came along with them.

**Comment by lcoombe** [comment]
Thanks so much for the update @charlesfeigin  - I'm very glad to hear that LongStitch worked well for you!
