### ISSUE TITLE
longstitch output format -- scaffolds?

### ISSUE THREAD

**Issue by RaverJay** [bcgsc/LongStitch#17]
Hey there!

I got a Flye draft assembly of some huge insecta genome and wanted to see if longstitch can improve the contiguity.

```
	Total length:	8358992738
	Fragments:	269616
	Fragments N50:	131274
	Largest frg:	1726048
	Scaffolds:	160
	Mean coverage:	14

```

Running longstitch yields the following stats:

```
--- Stats for: assembly.k32.w100.tigmint-ntLink.longstitch-scaffolds.fa ---
Num reads:   362840
Max len:     2111159
Median len:  4113.0
Mean len:    23391.976934737075
Readlen N50: 112478
Total bases: 8487544911
```

So just going by sequences in the output fasta, the number of contigs got increased.

After looking inside, I'm wondering if the output is in some kind of scaffolding format, where the scaffolds could be collapsed to contiguous sequences?

Best

**Comment by lcoombe** [comment]
Hi @RaverJay,

Did you use any lower length cut-off for counting the number of contigs/scaffolds? If you ran the default LongStitch pipeline, it includes a step `tigmint-long`, which corrects misassemblies and thus will make cuts in your input assembly. Then, the ntLink scaffolder is run after that. `tigmint-long` usually makes 2 cuts at each putative misassembly, which can generate some small pieces which could be inflating the count. You can take a look at the intermediate file containing the `tigmint-long` output to check this (should be in `*tigmint.fa`).

If you don't want any cuts made in your input assembly, you also have the option to just run scaffolding, and no correction with `ntLink`, and (optionally) `arks-long`.

The output is just a normal fasta format with scaffolds - the contigs input from `tigmint-long` scaffolded by ntLink, so contigs joined together with estimated gap sizes between.

Hope that helps - thank you for your interest in LongStitch!
Lauren

**Comment by RaverJay** [comment]
Hi Lauren,

No cutoff, just raw sequence numbers.
I'll try running only `ntLink` next

Thanks for clarifying!
Cheers

**Comment by lcoombe** [comment]
No worries!
