### ISSUE TITLE
Make error on longstitch run

### ISSUE THREAD

**Issue by Mondlii** [bcgsc/LongStitch#19]
Hi again,  I have been running longstitch using the following command: 

"longstitch run draft=Second_purge reads=ACSP644_PromethionFlonge_Porechopped.fasta_no_contaminants G=680MB (for genome size I have also tried removing the MB and just gave 680 and same error)" 

The tool runs for about 5 minutes and then gives the below error: 
" 
long-to-linked-pe v1.2.4: Using more than 6 threads does not scale, reverting to 6.                                                                                                             [2021-07-30 02:45:11] [ERROR] ACSP644_PromethionFlonge_Porechopped.fasta_no_contaminants.fa.gz source file is in invalid format!                                                                [M::mm_idx_gen::10.699*1.38] collected minimizers                                                                                                                                               [M::mm_idx_gen::14.303*2.07] sorted minimizers                                                                                                                                                  [M::main::14.303*2.07] loaded/built the index for 486 target sequence(s)                                                                                                                        [M::mm_mapopt_update::15.200*2.01] mid_occ = 469                                                                                                                                                [M::mm_idx_stat] kmer size: 15; skip: 10; is_hpc: 0; #seq: 486                                                                                                                                  [M::mm_idx_stat::15.675*1.98] distinct minimizers: 41987682 (59.91% are singletons); average occurrences: 3.132; average spacing: 5.195; total length: 683090277                                [M::main] Version: 2.21-r1071                                                                                                                                                                   [M::main] CMD: minimap2 -y -t8 -x map-ont --secondary=no Second_purge.fa -                                                                                                                      [M::main] Real time: 15.849 sec; CPU: 31.200 sec; Peak RSS: 4.042 GB                                                                                                                            Traceback (most recent call last):                                                                                                                                                                File "/home/FCAM/mxaba/miniconda3/envs/SLR/bin/share/tigmint-1.2.4-0/bin/tigmint_molecule_paf.py", line 141, in <module>                                                                          main()                                                                                                                                                                                        File "/home/FCAM/mxaba/miniconda3/envs/SLR/bin/share/tigmint-1.2.4-0/bin/tigmint_molecule_paf.py", line 138, in main                                                                              MolecIdentifierPaf().run()                                                                                                                                                                    File "/home/FCAM/mxaba/miniconda3/envs/SLR/bin/share/tigmint-1.2.4-0/bin/tigmint_molecule_paf.py", line 98, in run                                                                                self.print_new_molecule(prev_barcode, cur_intervals, out_molecules_file)                                                                                                                      File "/home/FCAM/mxaba/miniconda3/envs/SLR/bin/share/tigmint-1.2.4-0/bin/tigmint_molecule_paf.py", line 43, in print_new_molecule                                                                 barcode_match = re.search(r'^BX:Z:(\S+)', barcode)                                                                                                                                            File "/home/FCAM/mxaba/miniconda3/envs/SLR/lib/python3.9/re.py", line 201, in search                                                                                                              return _compile(pattern, flags).search(string)                                                                                                                                              TypeError: expected string or bytes-like object                                                                                                                                                 make[1]: *** [/home/FCAM/mxaba/miniconda3/envs/SLR/bin/share/tigmint-1.2.4-0/bin/tigmint-make:242: Second_purge.ACSP644_PromethionFlonge_Porechopped.fasta_no_contaminants.cut250.molecule.size$make[1]: *** Deleting file 'Second_purge.ACSP644_PromethionFlonge_Porechopped.fasta_no_contaminants.cut250.molecule.size2000.bed'                                                               make: *** [/home/FCAM/mxaba/miniconda3/envs/SLR/bin/share/longstitch-1.0.1-0/longstitch:155: Second_purge.cut250.tigmint.fa] Error 2     "

I have saved all the files including the bash script in the same directory. I even compressed the reads to the desired fa.gz format and the script used does not use extensions as in the instructions. I am looking for assistance on this because I never got this error when running ntLink (even though the output did not have a significant contiguity improvement from the draft.)

Thank you for your help and time.

**Comment by lcoombe** [comment]
Hi @Mondlii,

I see this error in your log file: 
```
[ERROR] ACSP644_PromethionFlonge_Porechopped.fasta_no_contaminants.fa.gz source file is in invalid format!
```
It looks like this file has an unexpected format - the most common cause for that would be using a multi-line fasta file vs. a single line fasta file. So I'd double-check your file format there. Alternatively, you can paste a few lines of your file here and I could try to take a look.

As for the genome size, the script is expecting the genome size without units, so for a 680Mb genome, use `G=680e6` or `G=680000000`

Hope that helps!
Lauren

**Comment by Mondlii** [comment]
Hi Laura, 

Thank you for your help. I had a mutlifasta file and I "converted it" to single line fasta using the command:

- awk '/^>/ {printf("\n%s\n",$0);next; } { printf("%s",$0);}  END {printf("\n");}' <file >outfile.fa

I then compressed the file to outfile.gz

I then cat the outfile (using  zcat Longstitch.fa.gz | head -5 ) and this is what it looks like: 

>072cbc1c-23e3-471e-bed2-b637ceeea421 runid=211987b51d11c179799528dfeabcba17112754b9 read=7 ch=21 start_time=2021-03-24T18:31:31Z flow_cell_id=AEQ639 protocol_group_id=2021MAR24_flngl_AEQ639 sample_id=2021MAR24_flngl_AEQ639                                                                                                                               ATCATATAGGGGGTATTTTAGTCATTAATTTCGAAAATCATGGTGGGGTCAGATTATGGCAAAATTTTGGAAGATTAGAGTCAAGTAGCGAGAAGTCTTGGCAGTCATTGATTAGGGAATTAGGGGCAAAATGAGCAATTTATTGCCTAAAATGCACATTATGATGTCAAATATTGATAAATGAGATATTATCATTATAGGATATCCCGGTAACCTTGATTTCAACGTGGATTACATTTGTCAGAGCGTGCACAT

(The window size is affecting the number of lines in the terminal it looks like).

I then re-ran and I got the same error so this means likely my conversion did not work? 

Thanks for your time.

**Comment by lcoombe** [comment]
Hi @Mondlii,

Yes, if you got the same error then it must mean that there was an issue with the conversion. Not sure how many lines are actually showing there, but if it is more than two, then the formatting is still off. Also, not sure if it's the formatting, but I don't see the `>` for the fasta file header?

I'd suggest just using `seqtk seq` for the conversion - a very useful toolkit, and then you can trust nothing strange is happening with the conversion.

Thanks for your interest in LongStitch!
Lauren

**Comment by Mondlii** [comment]
Hi @Lauren, 

Apologies for the late response I was waiting for resource availability before trying again. Using seqtk for the conversion seems to have worked as the run started without any errors so far. Thank you very much.

**Comment by lcoombe** [comment]
I'm glad to hear it's working after that conversion! Thanks for the update.
