### ISSUE TITLE
$draft.cut$cut.tigmint.fa is empty

### ISSUE THREAD

**Issue by rwhetten** [bcgsc/LongStitch#23]
I installed LongStitch from bioconda and tried running it with a draft assembly and a file of long read data (~25x coverage) comprised of a mix of PacBio and ONT reads, but the indexlr command fails with two statements, which are
cat: standard output: No such file or directory
[$date][WARNING] $draft.cut$cut.tigmint.fa is empty 
where $date is current date and time, and values of $draft and $cut reflect the name of the draft assembly and the cut size of the corresponding tigmint.fa file. The file is not empty - originally it was a soft link to a file with a different name, but copying the contents of that file to the name $draft.cut$cut.tigmint.fa does not change the output.

**Comment by lcoombe** [comment]
Hi @rwhetten,

Could you please post your full command and log? It would also be helpful to see a `ls` of your current working directory so I can double check that you are specifying the correct parameters in your command.
From there information here, the errors suggest that there was something wrong with the second stage (ntLink's indexlr) finding the output of Tigmint-long. The `*tigmint.fa` is in fact a soft-link with the pipeline, so that isn't the issue. Having more information, though, will be helpful for figuring it out.

Thank you for your interest in LongStitch!
Lauren

**Comment by rwhetten** [comment]
There are several empty output files, but the $draft.cut$cut.tigmint.fa file is not among them.
Command: 
longstitch run draft=DraftRef reads=pb.ont.clean t=50 G=22500000000
Full listing of output directory after run. The three files with timestamps of 13:22 on Sept 8 are the input files
ls -lh
total 43G
-rwxrwxrwx 1 ...   14 Sep  9 00:48 out.k32.w100.z1000.n2.scaffold.dot
-rwxrwxrwx 1 ...    0 Sep  9 00:48 out.k32.w100.z1000.pairs.tsv  ***EMPTY
-rwxrwxrwx 1 ...    0 Sep  9 02:20 out.k32.w100.z1000.stitch.path  ***EMPTY
-rwxrwxrwx 1 ... 402M Sep  8 20:46 pb.ont.clean.barcode-multiplicity.tsv
lrwxrwxrwx 1 ...   31 Sep  8 13:22 pb.ont.clean.fq.gz -> ../longreads/pb.ont.clean.fq.gz
-rwxrwxrwx 1 ...   22 Sep  8 20:46 pb.ont.clean.tigmint-long.params.tsv
lrwxrwxrwx 1 ...   86 Sep  8 21:27 DraftRef.cut250.tigmint.fa -> DraftRef.pb.ont.clean.cut250.molecule.size2000.trim0.window1000.spanauto.breaktigs.fa
-rwxrwxrwx 1 ...    0 Sep  8 21:27 DraftRef.cut250.tigmint.fa.k32.w100.tsv  ***EMPTY
lrwxrwxrwx 1 ...   67 Sep  9 02:30 DraftRef.cut250.tigmint.fa.k32.w100.z1000.ntLink.scaffolds.fa -> DraftRef.cut250.tigmint.fa.k32.w100.z1000.stitch.abyss-scaffold.fa
-rwxrwxrwx 1 ...  21G Sep  9 02:30 DraftRef.cut250.tigmint.fa.k32.w100.z1000.stitch.abyss-scaffold.fa
lrwxrwxrwx 1 ...   20 Sep  8 13:21 DraftRef.fa -> ../DraftRef.fa
lrwxrwxrwx 1 ...   24 Sep  8 13:21 DraftRef.fa.fai -> ../DraftRef.fa.fai
lrwxrwxrwx 1 ...   67 Sep  9 02:30 DraftRef.k32.w100.tigmint-ntLink.longstitch-scaffolds.fa -> DraftRef.cut250.tigmint.fa.k32.w100.z1000.stitch.abyss-scaffold.fa
-rwxrwxrwx 1 ... 744M Sep  8 20:58 DraftRef.pb.ont.clean.cut250.molecule.size2000.bed
-rwxrwxrwx 1 ...  21G Sep  8 21:27 DraftRef.pb.ont.clean.cut250.molecule.size2000.trim0.window1000.spanauto.breaktigs.fa
-rwxrwxrwx 1 ...  48M Sep  8 21:12 DraftRef.pb.ont.clean.cut250.molecule.size2000.trim0.window1000.spanauto.breaktigs.fa.bed

Output from the steps after minimap2 (which produces thousands of lines of output)
/media/software/miniconda3/envs/longstitch/bin/share/tigmint-1.2.4-0/bin/tigmint-cut -p50 -w1000 -t0 -f pb.ont.clean.tigmint-long.params.tsv -o DraftRef.pb.ont.clean.cut250.molecule.size2000.trim0.window1000.spanauto.breaktigs.fa DraftRef.fa DraftRef.pb.ont.clean.cut250.molecule.size2000.bed
Started at: 2021-09-08 20:58:09.975407
Reading contig lengths...
Finding breakpoints...
Cutting assembly at breakpoints...
DONE!
Ended at: 2021-09-08 21:27:05.229804
ln -sf DraftRef.pb.ont.clean.cut250.molecule.size2000.trim0.window1000.spanauto.breaktigs.fa DraftRef.cut250.tigmint.fa
make[1]: Leaving directory '/media/test'
ntLink scaffold target=DraftRef.cut250.tigmint.fa reads="pb.ont.clean.fq.gz" t=50 k=32 w=100 z=1000 n=2 conservative=True
make[1]: Entering directory '/media/test'
/media/hd03/software/miniconda3/envs/longstitch/bin/share/ntlink-1.0.1-0/src/indexlr --long --pos --strand -k 32 -w 100 -t 50 DraftRef.cut250.tigmint.fa > DraftRef.cut250.tigmint.fa.k32.w100.tsv
indexlr v1.3: Using more than 5 threads does not scale, reverting to 5.
cat: standard output: No such file or directory
[2021-09-08 21:27:05][WARNING] DraftRef.cut250.tigmint.fa is empty.
sh -c 'pigz -p50 -f -cd pb.ont.clean.fq.gz | \
/media/hd03/software/miniconda3/envs/longstitch/bin/share/ntlink-1.0.1-0/src/indexlr --long --pos --strand -k 32 -w 100 -t 50 - | \
  	/media/hd03/software/miniconda3/envs/longstitch/bin/share/ntlink-1.0.1-0/bin/ntlink_pair.py -p out.k32.w100.z1000 -n 2 -m DraftRef.cut250.tigmint.fa.k32.w100.tsv -s DraftRef.cut250.tigmint.fa  \
-k 32 -a 1 -z 1000 -f 10 -x 0 -'
indexlr v1.3: Using more than 5 threads does not scale, reverting to 5.
Running pairing stage of ntLink ...

Parameters:
	Reads TSV files:  ['-']
	-s  DraftRef.cut250.tigmint.fa
	-m  DraftRef.cut250.tigmint.fa.k32.w100.tsv
	-p  out.k32.w100.z1000
	-n  2
	-k  32
	-a  1
	-z  1000
	-f  10
	-x  0.0
2021-09-08 21:27:06.545116 : Reading minimizers DraftRef.cut250.tigmint.fa.k32.w100.tsv
2021-09-08 21:27:06.546067 : Reading fasta file DraftRef.cut250.tigmint.fa
2021-09-08 21:28:40.407360 : Finding pairs
2021-09-09 00:48:45.210929 : Building scaffold graph
2021-09-09 00:48:45.211708 : Filtering the graph
2021-09-09 00:48:45.212615 : Printing graph out.k32.w100.z1000.n2.scaffold.dot
2021-09-09 00:48:45.213113 : DONE!
sh -c 'cat DraftRef.cut250.tigmint.fa | \
cut -d " " -f1  | \
abyss-scaffold -k2 -n 2 -s1000 --min-gap 20 - out.k32.w100.z1000.n2.scaffold.dot 1> out.k32.w100.z1000.n2.abyss-scaffold.path 2>out.k32.w100.z1000.n2.abyss-scaffold.path.sterr'
sh -c 'cat DraftRef.cut250.tigmint.fa | \
cut -d " " -f1  | \
abyss-scaffold -k2 -n 3 -s1000 --min-gap 20 - out.k32.w100.z1000.n2.scaffold.dot 1> out.k32.w100.z1000.n3.abyss-scaffold.path 2>out.k32.w100.z1000.n3.abyss-scaffold.path.sterr'
sh -c 'cat DraftRef.cut250.tigmint.fa | \
cut -d " " -f1  | \
abyss-scaffold -k2 -n 4 -s1000 --min-gap 20 - out.k32.w100.z1000.n2.scaffold.dot 1> out.k32.w100.z1000.n4.abyss-scaffold.path 2>out.k32.w100.z1000.n4.abyss-scaffold.path.sterr'
sh -c 'cat DraftRef.cut250.tigmint.fa | \
cut -d " " -f1  | \
abyss-scaffold -k2 -n 5 -s1000 --min-gap 20 - out.k32.w100.z1000.n2.scaffold.dot 1> out.k32.w100.z1000.n5.abyss-scaffold.path 2>out.k32.w100.z1000.n5.abyss-scaffold.path.sterr'
sh -c 'cat DraftRef.cut250.tigmint.fa | \
cut -d " " -f1  | \
abyss-scaffold -k2 -n 6 -s1000 --min-gap 20 - out.k32.w100.z1000.n2.scaffold.dot 1> out.k32.w100.z1000.n6.abyss-scaffold.path 2>out.k32.w100.z1000.n6.abyss-scaffold.path.sterr'
sh -c 'cat DraftRef.cut250.tigmint.fa | \
cut -d " " -f1  | \
abyss-scaffold -k2 -n 7 -s1000 --min-gap 20 - out.k32.w100.z1000.n2.scaffold.dot 1> out.k32.w100.z1000.n7.abyss-scaffold.path 2>out.k32.w100.z1000.n7.abyss-scaffold.path.sterr'
sh -c 'cat DraftRef.cut250.tigmint.fa | \
cut -d " " -f1  | \
abyss-scaffold -k2 -n 8 -s1000 --min-gap 20 - out.k32.w100.z1000.n2.scaffold.dot 1> out.k32.w100.z1000.n8.abyss-scaffold.path 2>out.k32.w100.z1000.n8.abyss-scaffold.path.sterr'
sh -c 'cat DraftRef.cut250.tigmint.fa | \
cut -d " " -f1  | \
abyss-scaffold -k2 -n 9 -s1000 --min-gap 20 - out.k32.w100.z1000.n2.scaffold.dot 1> out.k32.w100.z1000.n9.abyss-scaffold.path 2>out.k32.w100.z1000.n9.abyss-scaffold.path.sterr'
sh -c 'cat DraftRef.cut250.tigmint.fa | \
cut -d " " -f1  | \
abyss-scaffold -k2 -n 10 -s1000 --min-gap 20 - out.k32.w100.z1000.n2.scaffold.dot 1> out.k32.w100.z1000.n10.abyss-scaffold.path 2>out.k32.w100.z1000.n10.abyss-scaffold.path.sterr'
/media/hd03/software/miniconda3/envs/longstitch/bin/share/ntlink-1.0.1-0/bin/ntlink_stitch_paths.py --min_n 2 --max_n 10  -p out \
-g out.k32.w100.z1000.n2.scaffold.dot --conservative out.k32.w100.z1000.n2.abyss-scaffold.path out.k32.w100.z1000.n3.abyss-scaffold.path out.k32.w100.z1000.n4.abyss-scaffold.path out.k32.w100.z1000.n5.abyss-scaffold.path out.k32.w100.z1000.n6.abyss-scaffold.path out.k32.w100.z1000.n7.abyss-scaffold.path out.k32.w100.z1000.n8.abyss-scaffold.path out.k32.w100.z1000.n9.abyss-scaffold.path out.k32.w100.z1000.n10.abyss-scaffold.path 1> out.k32.w100.z1000.stitch.path
Running ntLink stitch paths stage...

2021-09-09 02:20:48.418490  : Finding optimal n...
2021-09-09 02:20:48.421297  : Optimal n = 2 at N50 = 89916.0
2021-09-09 02:20:48.421324 : Building path graph
Printing paths for optimal N50, no stitching...

2021-09-09 02:20:48.421802 : Finding paths

Total number of components in graph: 0 

MergeContigs -k2 DraftRef.cut250.tigmint.fa out.k32.w100.z1000.stitch.path > DraftRef.cut250.tigmint.fa.k32.w100.z1000.stitch.abyss-scaffold.fa
rm out.k32.w100.z1000.n*.abyss-scaffold.path out.k32.w100.z1000.n*.abyss-scaffold.path.sterr
ln -sf DraftRef.cut250.tigmint.fa.k32.w100.z1000.stitch.abyss-scaffold.fa DraftRef.cut250.tigmint.fa.k32.w100.z1000.ntLink.scaffolds.fa
echo "Done ntLink! Final post-ntLink scaffolds can be found in: DraftRef.cut250.tigmint.fa.k32.w100.z1000.ntLink.scaffolds.fa"
Done ntLink! Final post-ntLink scaffolds can be found in: DraftRef.cut250.tigmint.fa.k32.w100.z1000.ntLink.scaffolds.fa
make[1]: Leaving directory '/media/test'
ln -sf DraftRef.cut250.tigmint.fa.k32.w100.z1000.stitch.abyss-scaffold.fa DraftRef.k32.w100.tigmint-ntLink.longstitch-scaffolds.fa
echo "Done LongStitch steps Tigmint-long and ntLink! Scaffolds can be found in: DraftRef.k32.w100.tigmint-ntLink.longstitch-scaffolds.fa"
Done LongStitch steps Tigmint-long and ntLink! Scaffolds can be found in: DraftRef.k32.w100.tigmint-ntLink.longstitch-scaffolds.fa

**Comment by lcoombe** [comment]
Thanks for this @rwhetten - Looking at it again, this line is quite strange: 
```
cat: standard output: No such file or directory
```
Since I can see that the file `DraftRef.pb.ont.clean.cut250.molecule.size2000.trim0.window1000.spanauto.breaktigs.fa` which is soft-linked to by the input file `DraftRef.cut250.tigmint.fa` is not empty. That's where the issue is coming - the Tigmint-long files look OK in terms of file size.

If you run that command independently of the full `longstitch` pipeline
```
/media/hd03/software/miniconda3/envs/longstitch/bin/share/ntlink-1.0.1-0/src/indexlr --long --pos --strand -k 32 -w 100 -t 50 DraftRef.cut250.tigmint.fa > DraftRef.cut250.tigmint.fa.k32.w100.tsv
```
Do you see the same error?

Have you successfully run our assembly demo? (https://github.com/bcgsc/LongStitch/tree/master/tests) That would also help to ensure that everything is properly set-up on your environment.

**Comment by rwhetten** [comment]
Regarding the assembly demo - the first part using test_scaffolds1.fa completed successfully, but the second part using test_scaffolds2.fa threw an error:
LINKS -f test_scaffolds2.cut250.tigmint.fa.k32.w150.z1000.stitch.abyss-scaffold.renamed.fa -s empty.fof -b test_scaffolds2.cut250.tigmint.fa.k32.w150.z1000.stitch.abyss-scaffold_c4_m8-10000_cut250_k20_r0.05_e30000_z1000_l4_a0.3 -l 4 -a 0.3 -z 1000
bash: LINKS: command not found

Regarding the indexlr command - I ran that using the full path to the executable, without activating the conda environment, and it completed successfully and created an output DraftRef.cut250.tigmint.fa.k32.w100.tsv file that contains information, without the odd error message about no such file or directory as stdout.

**Comment by lcoombe** [comment]
Thanks @rwhetten.

For the demo - that indicates that `LINKS` tool is not installed. In the past, we didn't include it in the `arcs` conda recipe, because it's a 'soft' dependency (ie. you can use the tool without it), but that's an oversight on my part to not have that in the `longstitch` conda recipe. I'll do a PR upstream to add that. In the meantime, `conda install links` will fix that.

I'm really not sure why you are getting that error only in your conda environment - to be clear if you run that command _within_ the conda environment (the indexlr command) you get an error, but if you run it _outside_ of the conda environment, you don't get the error? What machine are you running these commands on? Is it a 'fresh' conda environment?

**Comment by rwhetten** [comment]
I installed longstitch in a new conda environment a few days ago, although miniconda has been on the machine for a long time. I'll run the test again within the same conda environment I used before to confirm, but so far the result is that the odd errors occurred when I ran the command as part of the pipeline within the environment, but not when I ran the command outside the environment (and outside the make pipeline).

**Comment by lcoombe** [comment]
The other strange part is that you are not getting that error when you are running the demo in that same conda environment, which seems to suggest that it is specific to your own data. I haven't come across this error before, and I can't replicate it with any of our data. Can you provide any info about what machine you are running on? (Ie. RAM available, OS, etc)

@vlad0x00 - any idea what could be causing this error?

**Comment by rwhetten** [comment]
The machine has 384 GB RAM and runs Ubuntu 20.04, with eight 8-core Opteron processors. It seems that I get the error with my data sometimes but not others, and I'm wondering if it might be related to running the job in a directory on an external drive (connected via USB 3.0) versus running the job in a directory on an internal drive connected directly to the motherboard. I'll do another test overnight and provide an update Friday.

**Comment by rwhetten** [comment]
The pipeline is running in a directory on an internal drive, and has successfully passed the indexlr step to produce the $draft.cut$cut.tigmint.fa.k$k.w$w.tsv file. The soft links in the working directory point to copies of the reference genome, the genome.fai index, and the long reads fq.gz file that are stored on the external drive, so the issue does not seem to be the connectivity of the drive. 
One other question - the command I issued to start the run was 
`longstitch run draft=DraftRef reads=pb.ont.clean t=50 G=22500000000 k=40 w=500 &> output.log`
and the output tsv file is DraftRef.cut250.tigmint.fa.k32.w500.tsv. The values for k differ between the command and the output file name - is there a way to tell which k-value was actually used in the analysis?

**Comment by lcoombe** [comment]
Hi @rwhetten,

I'm glad to hear that on an internal drive, you've gotten past the problematic step! Using a external drives isn't something that do in our group, so that's useful information for future users.

For `k`, if you take a look at the help page (https://github.com/bcgsc/LongStitch#full-help-page), we use the variables `k_ntLink` to control the k value for the ntLink step of the pipeline, and `k_arks` to control the k value of the ARKS-long step. Since you are running the default pipeline (Tigmint-long + ntLink), if you are intending to change the k-mer size for computing minimizers in ntLink, use `k_ntLink`. The values of the parameters shown in the file names are what were used for the analysis - you could also see this by checking your output log.

I also often suggest running a dry-run (adding `-n` to your command), which prints out all the commands without actually running them. That sometimes helps to ensure that you see that you are passing in your parameters properly.

**Comment by rwhetten** [comment]
OK, thanks! I'll close the thread; I think we're done.

**Comment by lcoombe** [comment]
Great! I'm glad you were able to get past the issue :)

**Comment by vlad0x00** [comment]
Hi @rwhetten ,

Sorry for posting in a closed issue, I'm curious about the problem. Do you know what the filesystem is on your external drive? I was able to replicate indexlr malfunctioning on some filesystems so I thought that might be the cause. You can check the filesystem type using the `df -T` command on Linux, under the Type column. On MacOS, you can use`diskutil list`, the type will be under the TYPE column.

Cheers

**Comment by rwhetten** [comment]
The disk volume that gave the problem is listed as Type fuseblk in the output of df -T. Thanks for following up!

**Comment by vlad0x00** [comment]
FUSE is a filesystem interface so it doesn't tell us exactly which filesystem is underneath, but I suspect it is NTFS. Can you please verify by running `lsblk -o name,fstype`, the exact filesystem type would be printed under FSTYPE column.

**Comment by rwhetten** [comment]
Yes, the disk partition in question is NTFS.

**Comment by vlad0x00** [comment]
Thank you for confirming, I'll look into fixing this. NTFS is predominantly used by Windows, and we currently only test our tools on Linux and Mac, hence this issue. I think I know what the cause is, so it should work eventually.

**Comment by rwhetten** [comment]
For the moment, it would be helpful to add a note to the README on the Github page warning users not to use an NTFS-formatted disk for the working directory. Thanks!
