### ISSUE TITLE
Pipeline without Tigmint doesn't run

### ISSUE THREAD

**Issue by charlesfeigin** [bcgsc/LongStitch#25]
Hi!

I'm trying to scaffold an assembly with LongStitch using the ntLink-arks pipeline (i.e. without tigmint). Previously, I ran scaffolding with tigmint-ntLink-arks which ran end-to-end with pretty good results, but I'm interested in running without tigmint. I tried simply removing "tigmint" from the pipeline name as indicated in the usage message, but this causes the run to fail immediately with the following error:

**indexlr v1.3: Using more than 5 threads does not scale, reverting to 5.
[2021-11-02 10:31:43][ERROR] contigs.fa source file is in invalid format!
make[1]: *** [/home/cfeigin/.conda/envs/longstitch_v1.0.1_env/bin/share/ntlink-1.0.1-0/ntLink:141: contigs.fa.k32.w100.tsv] Error 1
make[1]: *** Deleting file 'contigs.fa.k32.w100.tsv'
make: *** [/home/cfeigin/.conda/envs/longstitch_v1.0.1_env/bin/share/longstitch-1.0.1-0/longstitch:168: contigs.fa.k32.w100.z1000.stitch.abyss-scaffold.fa] Error 2**

the command I ran is:

longstitch ntLink-arks t=32 draft=contigs reads=reads_all G=3000000000 2>longstitch_ntLinkArks.err 

where the contigs file is contigs.fa and the reads file is reads_all.fa.gz. I have also tried removing the G argument which is associated with tigmint. Again, the only difference from the full pipeline is using tigmint-ntLink-arks instead of ntLink-arks. Any help would be greatly appreciated.

**Comment by lcoombe** [comment]
Hi @charlesfeigin,

Can I ask which version of ntLink you are using? And is your `contigs.fa` file a single line fasta or multi-line? As of ntLink v1.1.0, we support multi-line fasta files, but prior to that the files had to be single-line, and that was the most common cause of this sort of error.

Let me know - thank you for your interest in LongStitch!
Lauren

**Comment by charlesfeigin** [comment]
Hi Lauren

That seems to have been it! The version was 1.0.1. The output of tigmint is single-line, so my older version of ntLink had no problem. After updating to 1.11 its past the point where it previously crashed. Thank you!

Best,
Charles

**Comment by lcoombe** [comment]
Excellent - I'm glad that solved it!
