### ISSUE TITLE
adjusting minimap2 arguments to accommodate different types of long reads

### ISSUE THREAD

**Issue by bishopia** [bcgsc/LongStitch#27]
I would like to use LongStitch to improve hybrid and HiFi read assemblies, but I noticed that when longstitch calls minimap2 it uses ``` -x map-ont```, not ```-x map-hifi```, which i would expect to produce better results. Do you know how I might adjust this? Thanks!

**Comment by lcoombe** [comment]
Hi @bishopia,

That's a good question and information that we should add to our README!

It's the Tigmint step that uses `minimap2`, and you can change to use `-x map-hifi` by specifying `longmap=hifi` in your longstitch command.

Hope that helps - thanks for your interest in LongStitch!
Lauren

**Comment by lcoombe** [comment]
Information added to README in c07c5cf
