### ISSUE TITLE
Broken Pipe Error

### ISSUE THREAD

**Issue by ChemaMD** [bcgsc/LongStitch#36]
Hi,

Congratulations for the useful piece of software. I'm getting an error when running the default pipeline, and I was wondering if you could help me to troubleshoot it.

The command I'm running is:

    module load anaconda3
    conda activate longstitch
    longstitch run draft=./Capitella_teleta_v1.0.dna.toplevel reads=./Capitella_Guppy5_pass_1kb t=6 G=330000000
    conda deactivate`

The error log:

    Variable OMP_NUM_THREADS has been set to 6
    tigmint-make tigmint-long draft=./Capitella_teleta_v1.0.dna.toplevel reads=./Capitella_Guppy5_pass_1kb cut=250 t=6 G=330000000 span=auto dist=auto
    make[1]: Entering directory '/data/scratch/btx333/Capitella/LongStitch'
    /data/home/btx333/.conda/envs/longstitch/bin/share/tigmint-1.2.5-0/bin/../src/long-to-linked-pe -l 250 -m2000 -g330000000 -s -b ./Capitella_Guppy5_pass_1kb.barcode-multiplicity.tsv --bx -t6 --fasta -f ./Capitella_Guppy5_pass_1kb.tigmint-long.params.tsv Capitella_Guppy5_pass_1kb.fq.gz | \
    minimap2 -y -t6 -x map-ont --secondary=no ./Capitella_teleta_v1.0.dna.toplevel.fa - | \
    /data/home/btx333/.conda/envs/longstitch/bin/share/tigmint-1.2.5-0/bin/tigmint_molecule_paf.py -q0 -s2000 -p ./Capitella_Guppy5_pass_1kb.tigmint-long.params.tsv - | sort -k1,1 -k2,2n -k3,3n > Capitella_teleta_v1.0.dna.toplevel../Capitella_Guppy5_pass_1kb.cut250.molecule.size2000.distauto.bed
    zsh:3: no such file or directory: Capitella_teleta_v1.0.dna.toplevel../Capitella_Guppy5_pass_1kb.cut250.molecule.size2000.distauto.bed
    [M::mm_idx_gen::6.324*1.71] collected minimizers
    [M::mm_idx_gen::7.353*2.26] sorted minimizers
    [M::main::7.353*2.26] loaded/built the index for 20803 target sequence(s)
    [M::mm_mapopt_update::7.891*2.17] mid_occ = 187
    [M::mm_idx_stat] kmer size: 15; skip: 10; is_hpc: 0; #seq: 20803
    [M::mm_idx_stat::8.285*2.12] distinct minimizers: 27341630 (70.80% are singletons); average occurrences: 1.901; average spacing: 6.411; total length: 333283208
    Traceback (most recent call last):
      File "/data/home/btx333/.conda/envs/longstitch/bin/share/tigmint-1.2.5-0/bin/tigmint_molecule_paf.py", line 141, in <module>
    main()
      File "/data/home/btx333/.conda/envs/longstitch/bin/share/tigmint-1.2.5-0/bin/tigmint_molecule_paf.py", line 138, in main
    MolecIdentifierPaf().run()
      File "/data/home/btx333/.conda/envs/longstitch/bin/share/tigmint-1.2.5-0/bin/tigmint_molecule_paf.py", line 91, in run
    self.print_new_molecule(prev_barcode, cur_intervals, out_molecules_file)
      File "/data/home/btx333/.conda/envs/longstitch/bin/share/tigmint-1.2.5-0/bin/tigmint_molecule_paf.py", line 66, in print_new_molecule
        self.print_current_molecule(ref, current_start, current_end, barcode_short,
      File "/data/home/btx333/.conda/envs/longstitch/bin/share/tigmint-1.2.5-0/bin/tigmint_molecule_paf.py", line 38, in print_current_molecule
    print(ref, start, end, barcode, num_reads, sep="\t", file=new_molec_file)
    BrokenPipeError: [Errno 32] Broken pipe
    time user=32.94s system=32.90s elapsed=79.07s cpu=83% memory=18 job= -l 250 -m2000 -g330000000 -s -b  --bx -t6 --fasta -f
    time user=242.37s system=8.77s elapsed=111.38s cpu=225% memory=3398 job=minimap2 -y -t6 -x map-ont --secondary=no  -
    time user=2.43s system=0.09s elapsed=111.05s cpu=2% memory=15 job= -q0 -s2000 -p ./Capitella_Guppy5_pass_1kb.tigmint-long.params.tsv -
    time user=0.00s system=0.00s elapsed=0.00s cpu=76% memory=1 job=
    make[1]: *** [/data/home/btx333/.conda/envs/longstitch/bin/share/tigmint-1.2.5-0/bin/tigmint-make:260: Capitella_teleta_v1.0.dna.toplevel../Capitella_Guppy5_pass_1kb.cut250.molecule.size2000.distauto.bed] Error 1
    make[1]: Leaving directory '/data/scratch/btx333/Capitella/LongStitch'
    make: *** [/data/home/btx333/.conda/envs/longstitch/bin/share/longstitch-1.0.1-1/longstitch:155: Capitella_teleta_v1.0.dna.toplevel.cut250.tigmint.fa] Error 2

Any idea what might be causing this?

Thanks!

Chema

**Comment by lcoombe** [comment]
Hello Chema,

For the command, since `longstitch` is a Makefile that drives the pipeline, don't include any paths in the input files. For example, change your command to:
```
longstitch run draft=Capitella_teleta_v1.0.dna.toplevel reads=Capitella_Guppy5_pass_1kb t=6 G=330000000
```
That's just because the `draft` and `reads` values supplied are used for various file output names in the pipeline as well as specifying input files. If you have files that are in a different directory, you can soft-link them to your current working directory.

I hope that helps - thank you for your interest in LongStitch!
Lauren
