### ISSUE TITLE
ImportError for pybedtools

### ISSUE THREAD

**Issue by 123chenshixin** [bcgsc/LongStitch#45]
Hi, I run LongStitch to scaffold my contig assemble by using Nanopore data. My command is below:
`longstitch run draft=contig reads=Ach_clean t=56 out_prefix=longstitch G=4e8`
After running minimap2 successfully, I get the error.

> [M::main] CMD: minimap2 -y -t56 -x map-ont --secondary=no contig.fa -
[M::main] Real time: 2005.910 sec; CPU: 23560.763 sec; Peak RSS: 6.320 GB
time user=659.04s system=247.48s elapsed=1990.17s cpu=45% memory=10 job= -l 250 -m2000 -g4e8 -s -b Ach_clean.barcode-multiplicity.tsv --bx -t56  -f
time user=21746.31s system=1814.89s elapsed=2006.50s cpu=1174% memory=6471 job=minimap2 -y -t56 -x map-ont --secondary=no contig.fa -
time user=1539.28s system=21.93s elapsed=2006.52s cpu=77% memory=15 job= -q0 -s2000 -p Ach_clean.tigmint-long.params.tsv -
time user=297.36s system=1.42s elapsed=2144.44s cpu=13% memory=11 job=
Traceback (most recent call last):
  File "/home/cxs3_z4/software/miniconda3/bin/share/tigmint-1.2.6-1/bin/tigmint-cut", line 14, in <module>
    import pybedtools
ModuleNotFoundError: No module named 'pybedtools'
make[1]: *** [/home/cxs3_z4/software/miniconda3/bin/share/tigmint-1.2.6-1/bin/tigmint-make:323: contig.Ach_clean.cut250.molecule.size2000.distauto.trim0.window1000.spanauto.breaktigs.fa] Error 1
make: *** [/home/cxs3_z4/software/miniconda3/bin/share/longstitch-1.0.1-1/longstitch:155: contig.cut250.tigmint.fa] Error 2

Then I run the command as `pip install pybedtools` and rerun again. However, I get the problem:

> Traceback (most recent call last):
  File "/home/cxs3_z4/software/miniconda3/bin/share/tigmint-1.2.6-1/bin/tigmint-cut", line 14, in <module>
    import pybedtools
  File "/home/cxs3_z4/software/Python-3.9.0/lib/python3.9/site-packages/pybedtools/__init__.py", line 8, in <module>
    from .cbedtools import (
ImportError: /home/cxs3_z4/software/Python-3.9.0/lib/python3.9/site-packages/pybedtools/cbedtools.cpython-39-x86_64-linux-gnu.so: undefined symbol: _ZSt28__throw_bad_array_new_lengthv
make[1]: *** [/home/cxs3_z4/software/miniconda3/bin/share/tigmint-1.2.6-1/bin/tigmint-make:323: contig.Ach_clean.cut250.molecule.size2000.distauto.trim0.window1000.spanauto.breaktigs.fa] Error 1
make: *** [/home/cxs3_z4/software/miniconda3/bin/share/longstitch-1.0.1-1/longstitch:155: contig.cut250.tigmint.fa] Error 2

What suggestion could you help me? I will be very grateful!

**Comment by lcoombe** [comment]
Hi @123chenshixin,

Could you confirm how you installed LongStitch? Was it via conda? If so, did you have that environment properly activated when you started the run? I ask because the LongStitch conda recipe does have pybedtools as a dependency already, and there may be issues due to mixing dependencies in the environment if you subsequently try a `pip install` 

Thanks for your interest in LongStitch!
Lauren
