### ISSUE TITLE
ntLink via brew failed

### ISSUE THREAD

**Issue by giuliaguidi** [bcgsc/LongStitch#47]
FYI ntLink requires installation from the source code as the brew link is out of scope.

**Comment by lcoombe** [comment]
Hi @giuliaguidi,

Thanks for reaching out! Would you mind elaborating on what you mean by "out of scope"?

Do note that installing via conda is a great alternative to installing from the source code as well.

**Comment by giuliaguidi** [comment]
This is the error I get when trying to install it using brew:

```
curl: (22) The requested URL returned error: 404 
Error: ntlink: Failed to download resource "ntlink_bottle_manifest"
Download failed: https://ghcr.io/v2/brewsci/bio/ntlink/manifests/1.2.1
```

I was able to install it using the source code.

**Comment by lcoombe** [comment]
Thanks very much for flagging this! I took a look at the homebrew-bio repo, and it looks like bottles aren't being uploaded properly following recent updates (https://github.com/brewsci/homebrew-bio) - I'll follow up with the maintainers there to hopefully get it all sorted out.

**Comment by giuliaguidi** [comment]
Thank you!
