### ISSUE TITLE
gunzip: standard input is a terminal -- ignoring

### ISSUE THREAD

**Issue by giuliaguidi** [bcgsc/LongStitch#48]
Hi, 

I would like to run LongStitch on some contigs I generated but I get the following error right at the beginning `gunzip: standard input is a terminal -- ignoring`. 

Any idea what could be the problem? The test run you provided doesn't show this error. 

```
gguidi@Giulias-MBP longstitch-1.0.2 % ./longstitch run draft=celegans.elba.contigs reads=celegans_hifi_sim.40x.fa.gz G=101e6 
tigmint-make tigmint-long draft=celegans.elba.contigs reads=celegans_hifi_sim.40x.fa.gz cut=250 t=8 G=101e6 span=auto dist=auto
sh -c 'gunzip -c  | \
	/usr/local/Cellar/tigmint/1.2.5/libexec/bin/tigmint_estimate_dist.py - -n 1000000 -o celegans_hifi_sim.40x.fa.gz.tigmint-long.params.tsv'
gunzip: standard input is a terminal -- ignoring
Traceback (most recent call last):
```

Thank you!

**Comment by lcoombe** [comment]
Hi @giuliaguidi,

It looks like the issue is just with how you're specifying the reads in your command - you have to omit the suffix. 
Ie - this should work:
```
./longstitch run draft=celegans.elba.contigs reads=celegans_hifi_sim.40x G=101e6
```

Let me know if that fixes it for you - thank you for your interest in LongStitch!
Lauren

**Comment by giuliaguidi** [comment]
That worked—thank you very much!

Giulia

**Comment by giuliaguidi** [comment]
One last question (hopefully, sorry)—the pipeline mostly completes and then I get this error at the end:

```
2022-06-03 12:44:40.030798 : Printing graph celegans.elba.contigs.cut250.tigmint.fa.k32.w100.z1000.n2.scaffold.dot
2022-06-03 12:44:40.082196 : DONE!
sh -c 'cat celegans.elba.contigs.cut250.tigmint.fa | \
	cut -d " " -f1  | \
	abyss-scaffold -k2 -n 2 -s1000 --min-gap 20 - celegans.elba.contigs.cut250.tigmint.fa.k32.w100.z1000.n2.scaffold.dot 1> celegans.elba.contigs.cut250.tigmint.fa.k32.w100.z1000.n2.abyss-scaffold.path 2>celegans.elba.contigs.cut250.tigmint.fa.k32.w100.z1000.n2.abyss-scaffold.path.sterr'
make[1]: *** [celegans.elba.contigs.cut250.tigmint.fa.k32.w100.z1000.n2.abyss-scaffold.path] Error 127
make[1]: *** Deleting file `celegans.elba.contigs.cut250.tigmint.fa.k32.w100.z1000.n2.abyss-scaffold.path'
make: *** [celegans.elba.contigs.cut250.tigmint.fa.k32.w100.z1000.stitch.abyss-scaffold.fa] Error 2
```

**Comment by lcoombe** [comment]
Huh - I don't recall seeing that error before.. Just double checking - so you did get a successful run from the test demo right? Therefore you do have `abyss-scaffold` (packaged in ABySS) installed?

Is there any error message logged in the file `celegans.elba.contigs.cut250.tigmint.fa.k32.w100.z1000.n2.abyss-scaffold.path.sterr`?

**Comment by giuliaguidi** [comment]
Oh, silly me. I thought I installed it but I must have just thought about doing that. I apologize, the error is gone and I got to the end of the pipeline.

Thank you very much for the assistance and quick replies!

**Comment by lcoombe** [comment]
Very glad that you got a successful run!
You're very welcome - I'm always happy to help :)
