### ISSUE TITLE
N sequences in scaffolded contig

### ISSUE THREAD

**Issue by cytham** [bcgsc/LongStitch#49]
Hi, I observed the presence of a 10 kb 'N' sequence stretch in one of my scaffolded contig. May I know what this means?

The attached image shows the right region of the 10kb N sequence.

<img width="593" alt="Screenshot 2022-06-28 at 12 24 04 PM" src="https://user-images.githubusercontent.com/25361260/176092036-c3e907c1-8be9-47e2-bef0-197505d4cd0f.png">

**Comment by lcoombe** [comment]
Hi @cytham,

The ntLink (and ARCS-long) scaffolding steps of LongStitch use the input long reads to infer joins between adjacent contigs, and join them with a gap (sequence of N's) between them. They estimate the size of that gap - in the case of ntLink, it's based on the mapping coordinates of the supporting reads to the incident contigs. So in this case, based on those mappings it estimated that there was a 10kb gap between joined sequences.

I hope that helps - thank you for your interest in LongStitch!
Lauren

**Comment by cytham** [comment]
@lcoombe Thanks for your explanation. Meaning to say, if I analyse the supporting reads, I should be able to create a 10kb consensus sequence to fill the gap?

**Comment by cytham** [comment]
Hi @lcoombe,

Thanks for your reply. Looking forward to the new features :)

Will the 'gap-filling' feature of ntLink be accessible through LongStitch?

**Comment by lcoombe** [comment]
Hi @cytham,

Good question! Currently it is not, but I'll be integrating that option into LongStitch - I can look at doing that this week. 
In the meantime the (somewhat hacky) workaround would be to run Tigmint-long using the `longstitch` makefile, then run the makefile command with a dry-run (`-n`) to see what the ntLink command would look like, then add the `gap_fill` target. I know that's a bit fiddly and confusing though, so if that doesn't make sense, I'll let you know when LongStitch has the gap-filling option incorporated.

**Comment by cytham** [comment]
@lcoombe Great! Thanks

**Comment by lcoombe** [comment]
Hi @cytham,
Just an update that the newest release of LongStitch (v1.0.3) includes an option to run the gap-filling feature of ntLink. You just have to ensure that you are using ntLink v1.3.3+ and specify `gap_fill=True` in your `longstitch` command. Details of all this can also be found in the README.
Thanks!
