### ISSUE TITLE
MAKE help text instead of Longstitch

### ISSUE THREAD

**Issue by mrmrwinter** [bcgsc/LongStitch#52]
Hi, just making you aware, when i run `longstitch -h` it prints the help message for GNU MAKE, not longstitch.

**Comment by lcoombe** [comment]
Hi @mrmrwinter,

Thanks for noting that! For the benefit of other users, running `longstitch help` will print out the help page for longstitch. Using `-h` prints out the GNU MAKE help message since `longstitch` is driven by a makefile.
