### ISSUE TITLE
Problems with conda distribution of LongStitch

### ISSUE THREAD

**Issue by BirdmanRidesAgain** [bcgsc/LongStitch#53]
Hey!
I installed LongStitch using your conda distribution (conda install -c bioconda -c conda-forge longstitch), but I've been having some errors with the dependencies. I've attached a plaintext .yml file for the associated environment to this issue.

The command I'm running is as follows: longstitch run t=70 draft=houbaraONT_assembly-racon reads=houbaraONT_trimreads G=1200000000
The files are all present, there's sufficient memory and threads to complete the process, but I get the following error with numpy as the program begins to call Tigmint:

> Traceback (most recent call last):
>   File "/home/kcollier/miniconda3/envs/LS/bin/share/tigmint-1.2.6-3/bin/tigmint_estimate_dist.py", line 9, in <module>
>     import numpy as np
> ModuleNotFoundError: No module named 'numpy'
> make[1]: *** [/home/kcollier/miniconda3/envs/LS/bin/share/tigmint-1.2.6-3/bin/tigmint-make:270: houbaraONT_trimreads.tigmint-long.params.tsv] Error 1
> make[1]: Leaving directory '/mnt/data/kcollier/ONT-data/HoubaraONT'
> make: *** [/home/kcollier/miniconda3/envs/LS/bin/share/longstitch-1.0.3-0/longstitch:183: houbaraONT_assembly-racon.cut250.tigmint.fa] Error 2

The full output is included below. I'm running this in an OVH server, and can provide any other information that might be relevant to figuring this out.
Thanks in advance for your time.

> longstitch run t=70 draft=houbaraONT_assembly-racon reads=houbaraONT_trimreads G=1200000000
> tigmint-make tigmint-long draft=houbaraONT_assembly-racon reads=houbaraONT_trimreads cut=250 t=70 G=1200000000 span=auto dist=auto
> make[1]: Entering directory '/mnt/data/kcollier/ONT-data/HoubaraONT'
> PYTHONPATH=/home/kcollier/miniconda3/envs/LS/bin/share/tigmint-1.2.6-3/bin/../src/btllib/install/python/  /home/kcollier/miniconda3/envs/LS/bin/share/tigmint-1.2.6-3/bin/tigmint_estimate_dist.py houbaraONT_trimreads.fastq -n 1000000 -o houbaraONT_trimreads.tigmint-long.params.tsv
> Traceback (most recent call last):
>   File "/home/kcollier/miniconda3/envs/LS/bin/share/tigmint-1.2.6-3/bin/tigmint_estimate_dist.py", line 9, in <module>
>     import numpy as np
> ModuleNotFoundError: No module named 'numpy'
> make[1]: *** [/home/kcollier/miniconda3/envs/LS/bin/share/tigmint-1.2.6-3/bin/tigmint-make:270: houbaraONT_trimreads.tigmint-long.params.tsv] Error 1
> make[1]: Leaving directory '/mnt/data/kcollier/ONT-data/HoubaraONT'
> make: *** [/home/kcollier/miniconda3/envs/LS/bin/share/longstitch-1.0.3-0/longstitch:183: houbaraONT_assembly-racon.cut250.tigmint.fa] Error 2
> 
[LongStitch-error.yml.txt](https://github.com/bcgsc/LongStitch/files/9771023/LongStitch-error.yml.txt)

**Comment by lcoombe** [comment]
Hello @BirdmanRidesAgain,

Strange - it appears as though the `numpy` module cannot be found, despite it being installed in your environment, based on the `yml.txt` file that you attached.

Would you be able to do a couple of sanity checks? All of these would be in your activated LongStitch conda environment:
* Run `python3 -c 'import numpy'` 
* Run `which python3`
* Check that the conda `bin` is first on your PATH with `echo $PATH`

I'm hoping those little tests will help us to be completely sure that the python3 that you intended is first on your PATH - if it isn't then the scripts above could be using a python installation that doesn't have the module dependencies installed.

Thanks for your interest in LongStitch!
Lauren

**Comment by BirdmanRidesAgain** [comment]
First, thanks for replying.

Secondly,` "python3 -c 'import numpy'"` produces the following output:

> Traceback (most recent call last):
>   File "<string>", line 1, in <module>
> ModuleNotFoundError: No module named 'numpy'

`which python3`
Tells me that it is looking for python in my conda distribution, although not in the LS environment:
/home/kcollier/miniconda3/bin/python3

Finally, the path variable is a titanic string with many, many repeats of "/home/kcollier/miniconda3/bin:", right at the very beginning. I cut the copy/pasted version down to size, but the "..." would just be many, many repeats of that path statement. I feel like that's somewhat unhealthy for my processes, but I'm also _pretty sure_ it's using the conda version of python3.

> /home/kcollier/miniconda3/bin:/home/kcollier/miniconda3/condabin:/usr/local/ncbi/sra-tools/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin

**Comment by BirdmanRidesAgain** [comment]
Alright, yes. Running which python3 with LS active produces the following results, which seems more reasonable. The path is unchanged though.

> /home/kcollier/miniconda3/envs/LS/bin/python3

**Comment by lcoombe** [comment]
So now if you repeat the above test (`python3 -c 'import numpy'`), what do you get now? Would you also mind pasting the result of `echo $PATH` after activating the environment? If the first python3 it finds is now the one in your "LS" environment, then the above "LS" bin should now be on your PATH.

Also to clarify, did you run `conda activate LS` prior to running LongStitch initially? Do ensure that you do that - because the issue appears to be that the python3 that was being found was not the one in your LS environment, so it's important that this python3 installation is found first, as it has the required installed modules.

**Comment by BirdmanRidesAgain** [comment]
I think I've found the error. I use `screen` to manage different processes on the cluster, and running `conda activate LS && which python3` gave me differing output when I ran it in the base environment:

> /home/kcollier/miniconda3/envs/LS/bin/python3

 vs. in an older screen: 

> /home/kcollier/miniconda3/bin/python3

 My path statement is also much more reasonably sized in base (included at the bottom), so the issue seems to be with how `screen` is interacting with conda on the cluster. Thanks for helping me troubleshoot it, though; that probably would've taken me a lot longer to figure out without some pointers!

>  /home/kcollier/miniconda3/envs/LS/bin:/home/kcollier/miniconda3/condabin:/usr/local/ncbi/sra-tools/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin:

**Comment by lcoombe** [comment]
Excellent - glad to hear that you were able to figure it out! :)

**Comment by BirdmanRidesAgain** [comment]
Hi! Sorry to reopen this issue again, but something else very weird is going on with longstitch. I was attempting to scaffold a new assembly using the same environment and basic syntax as before, when I got the (long) output copied below - a partial run, followed by a broken pipe error resulting in a premature Exit status 2.

To verify that this wasn't a syntax or input file issue, I attempted to rerun the scaffold command using input files and syntax (included below) which had successfully run before. 

`longstitch run t=6 draft=houbaraONT_assembly-racon reads=houbaraONT_trimreads G=1200000000`

This had no effect on the run's output or early termination. Remembering the issues with importing python packages last time, I also tried to run LS both inside and outside of a screen, which similarly had no effect on the output. I was wondering if you had any input, or could at least help me interpret what, exactly, the error LS is throwing means.


(I also attempted to use the latest tarball distribution of LS, along with the brew dependencies, but that was also met with failure. I think that might be a syntax issue, though, and if you have any pointers in that regard, I would appreciate the help.)
`bash ../PATH/TO/Longstitch-master/.github/longstitch run t=6 draft=houbaraONT_assembly-racon reads=houbaraONT_trimreads G=1200000000`


Thanks again for helping with this - I do genuinely find your package to be an incredibly powerful tool for genome scaffolding, and I was pretty vexed to find it not working this morning.


### VERBATIM ERROR MESSAGES ###

```
tigmint-make tigmint-long draft=../racon/houbaraONT_assembly-racon reads=../../.                                                                                                             ./ONT-data/HoubaraONT/houbaraONT_trimreads cut=250 t=6 G=1200000000 span=auto di                                                                                                             st=auto
make[1]: Entering directory '/mnt/data/kcollier/assemblies/HoubaraONT/LS'
/home/kcollier/miniconda3/envs/LS/bin/share/tigmint-1.2.6-3/bin/../src/long-to-l                                                                                                             inked-pe -l 250 -m2000 -g1200000000 -s -b ../../../ONT-data/HoubaraONT/houbaraON                                                                                                             T_trimreads.barcode-multiplicity.tsv --bx -t6 --fasta -f ../../../ONT-data/Houba                                                                                                             raONT/houbaraONT_trimreads.tigmint-long.params.tsv ../../../ONT-data/HoubaraONT/                                                                                                             houbaraONT_trimreads.fq.gz | \
minimap2 -y -t6 -x map-ont --secondary=no ../racon/houbaraONT_assembly-racon.fa                                                                                                              - | \
/home/kcollier/miniconda3/envs/LS/bin/share/tigmint-1.2.6-3/bin/tigmint_molecule                                                                                                             _paf.py -q0 -s2000 -p ../../../ONT-data/HoubaraONT/houbaraONT_trimreads.tigmint-                                                                                                             long.params.tsv - | sort -k1,1 -k2,2n -k3,3n  > ../racon/houbaraONT_assembly-rac                                                                                                             on.../../../ONT-data/HoubaraONT/houbaraONT_trimreads.cut250.molecule.size2000.di                                                                                                             stauto.bed
zsh:3: no such file or directory: ../racon/houbaraONT_assembly-racon.../../../ON                                                                                                             T-data/HoubaraONT/houbaraONT_trimreads.cut250.molecule.size2000.distauto.bed
[M::mm_idx_gen::19.942*1.62] collected minimizers
[M::mm_idx_gen::22.140*2.05] sorted minimizers
[M::main::22.140*2.05] loaded/built the index for 2157 target sequence(s)
[M::mm_mapopt_update::23.877*1.97] mid_occ = 152
[M::mm_idx_stat] kmer size: 15; skip: 10; is_hpc: 0; #seq: 2157
[M::mm_idx_stat::24.876*1.93] distinct minimizers: 77303709 (49.57% are singletons); average occurrences: 2.861; average spacing: 5.328; total length: 1178290473
Traceback (most recent call last):
  File "/home/kcollier/miniconda3/envs/LS/bin/share/tigmint-1.2.6-3/bin/tigmint_                                                                                                             molecule_paf.py", line 141, in <module>
    main()
  File "/home/kcollier/miniconda3/envs/LS/bin/share/tigmint-1.2.6-3/bin/tigmint_                                                                                                             molecule_paf.py", line 138, in main
    MolecIdentifierPaf().run()
  File "/home/kcollier/miniconda3/envs/LS/bin/share/tigmint-1.2.6-3/bin/tigmint_                                                                                                             molecule_paf.py", line 91, in run
    self.print_new_molecule(prev_barcode, cur_intervals, out_molecules_file)
  File "/home/kcollier/miniconda3/envs/LS/bin/share/tigmint-1.2.6-3/bin/tigmint_                                                                                                             molecule_paf.py", line 66, in print_new_molecule
    self.print_current_molecule(ref, current_start, current_end, barcode_short,
  File "/home/kcollier/miniconda3/envs/LS/bin/share/tigmint-1.2.6-3/bin/tigmint_                                                                                                             molecule_paf.py", line 38, in print_current_molecule
    print(ref, start, end, barcode, num_reads, sep="\t", file=new_molec_file)
BrokenPipeError: [Errno 32] Broken pipe
time user=7.44s system=3.55s elapsed=49.08s cpu=22% memory=6 job= -l 250 -m2000                                                                                                              -g1200000000 -s -b  --bx -t6 --fasta -f
time user=159.49s system=8.54s elapsed=49.08s cpu=342% memory=9098 job=minimap2                                                                                                              -y -t6 -x map-ont --secondary=no  -
time user=0.08s system=0.01s elapsed=48.63s cpu=0% memory=18 job= -q0 -s2000 -p                                                                                                               -
time user=0.00s system=0.00s elapsed=0.00s cpu=78% memory=2 job=
make[1]: *** [/home/kcollier/miniconda3/envs/LS/bin/share/tigmint-1.2.6-3/bin/ti                                                                                                             gmint-make:281: ../racon/houbaraONT_assembly-racon.../../../ONT-data/HoubaraONT/                                                                                                             houbaraONT_trimreads.cut250.molecule.size2000.distauto.bed] Error 1
make[1]: Leaving directory '/mnt/data/kcollier/assemblies/HoubaraONT/LS'
make: *** [/home/kcollier/miniconda3/envs/LS/bin/share/longstitch-1.0.3-0/longst                                                                                                             itch:183: ../racon/houbaraONT_assembly-racon.cut250.tigmint.fa] Error 2

```

**Comment by lcoombe** [comment]
Hi @BirdmanRidesAgain,

I see an earlier error message here: 
```
zsh:3: no such file or directory: ../racon/houbaraONT_assembly-racon.../../../ON                                                                                                             T-data/HoubaraONT/houbaraONT_trimreads.cut250.molecule.size2000.distauto.bed
```

In the help page we note:
```
	- Ensure that all input files are in the current working directory, making soft-links if needed
```
So, looks like the error is due to you using relative paths vs. having the input files in your current working directory (ex.  I see `draft=../racon/houbaraONT_assembly-racon` in the log message above). Try making those soft-links prior to the run and it should fix the issue. I can also add something more to the README to make that requirement more clear!

**Comment by BirdmanRidesAgain** [comment]
Well, don't I feel dumb now. Thank you, that solved the problem!
