### ISSUE TITLE
make: *** No rule to make target 'draft.fasta.fa', needed by 'draft.fasta.cut250.tigmint.fa'.  Stop.`

### ISSUE THREAD

**Issue by BenAawf** [bcgsc/LongStitch#54]
Thank you so much for such an amazing tool.

I'm facing a problem running LongStitch through conda: This is my command: to run the pipeline: `longstitch run draft=draft.fasta reads=all5ont.fastq.gz G=1100000000
make: *** No rule to make target 'draft.fasta.fa', needed by 'draft.fasta.cut250.tigmint.fa'.  Stop.`

I googled the issue, but I couldn't find any solution. And tried to check if there is any missing dependency package for tigmint.

Al dependency seems to work fine in the current conda env.
and all input files in the same directory.
Any help is very appreciated.
Thank you 
BenAawf

**Comment by lcoombe** [comment]
Hello @BenAawf,

For your longstitch command, we require that you don't include the suffixes of the input file names.

This section of the help page describes the requirements:
```
	General options (required):
	draft			draft name [draft]. File must have .fa extension
	reads			read name [reads]. File must have .fq.gz or .fa.gz extension
```
So, i'd suggest that you create soft-links to make input files with the expected extensions:
```
ln -s draft.fasta draft.fa
ln -s all5ont.fastq.gz all5ont.fq.gz
```
Then, your command would be:
```
longstitch run draft=draft reads=all5ont G=1100000000
```
There's also another example here in case it helps to clear things up more: https://github.com/bcgsc/LongStitch#example-command 

I hope that helps - thank you very much for your interest and support for LongStitch! :) 
Lauren

**Comment by BenAawf** [comment]
Thank you, @lcoombe it works. I did not pay attention to that requirement.

**Comment by lcoombe** [comment]
Glad it's working for you now!
