### ISSUE TITLE
conda installation issues

### ISSUE THREAD

**Issue by Laura-Alex** [bcgsc/LongStitch#59]
Hello!

I seem to be having an issue with installing longstitch via conda. This happens even with a newly-created conda environment.

The error message:
```
Collecting package metadata (current_repodata.json): done
Solving environment: failed with initial frozen solve. Retrying with flexible solve.
Solving environment: failed with repodata from current_repodata.json, will retry with next repodata source.
Collecting package metadata (repodata.json): done
Solving environment: 
```

(and then it times out)

What I've tried:
-updating conda from 4.10 to 4.12 (didn't work)
-checking channel priority as suggested in Issue#18 (it was already bioconda as highest priority, followed by conda-forge; didn't work)
-specifying channels or not when trying to install, e.g.
```
conda install longstitch
conda install -c bioconda conda-forge longstitch
conda install -c bioconda longstitch
```
(it didn't work)

I am not having this issue with all packages (e.g. 'prokka' worked fine when I tried to install it again in another environment) but seq-seq-pan, for instance, didn't work in the same way. I would appreciate some help on the matter!

Kind regards,

Laura

**Comment by lcoombe** [comment]
Hi Laura,

Is it your server that is timing out? After how long? I find that conda can be quite slow in solving the environment depending on various factors like your system and the other tools already present in your environment. But, it will complete the installation if given enough time. Anything that you could do to prevent a time-out (keep your internet connection active, etc) would likely help. Also note that you should have `-c` before each specified channel.

Another option is to try to install using `mamba` (https://anaconda.org/conda-forge/mamba). It is faster than `conda` and installs all the same packages. You can install it in a conda environment with `conda install mamba python=3.9`, and then run `mamba install -c bioconda -c conda-forge longstitch`.

I hope that helps - thank you for your interest in LongStitch!
Lauren

**Comment by Laura-Alex** [comment]
Hello Lauren,

Mamba solved the issue beautifully! Before then, it hung up at 10-20 minutes or so.
Stumbled my way into another bug afterwards. It's now solved, but just leaving it here in case anyone finds it helpful:
After installation, longstitch seemed to start from the command line, but not when submitting it as a job on the server. Then, it stopped in a similar way to Issue#44. Running from the command line wasn't super useful to me since I didn't know whether there would be enough memory. Since the previous issue mentioned symlinks, what helped me was specifying the path in the job script besides activating the environment. Like:
`PATH=$HOME/.conda/envs/long-stitch/bin:$PATH`

Thank you for your help! Looks like it's finished running now, and I'll get to see the results!

**Comment by lcoombe** [comment]
Thanks for the info Laura, and I'm glad that you got LongStitch installed and running!
