### ISSUE TITLE
output filenames?

### ISSUE THREAD

**Issue by margaretc-ho** [bcgsc/LongStitch#61]
I am trying to decipher the files that are output from longstitch
![image](https://user-images.githubusercontent.com/112181510/215528205-14742829-5e96-49b0-ba9b-1431641a29b4.png)

If this was my command:
 				  longstitch \
 				  tigmint-ntLink-arks \
 				  k_ntLink=$40 \
 				  w=500 \
 				  gap_fill=True \
 				  draft=tc.contigs \
 				  reads=Tc_combined_run_all_pass.minION.atleast10kb \
 				   G=60000000 \
Which filename includes the final longstitched contigs with gap fills? I am also confused because the filenames are sorted from most recent to older (based on timestamp created).

Thanks in advance!

**Comment by lcoombe** [comment]
Hi @margaretc-ho,

If you take a look in the log messages from the LongStitch, there should be a final message that tells you which the final file is. 
The image above it cut off a bit, but the final scaffolds in this case are in the file with the suffix `.tigmint-ntLink-arks.longstitch-scaffolds.fa`. It's a soft-link to the file with a longer file name (containing the final scaffolds).

Thanks for your interest in LongStitch!
Lauren

**Comment by margaretc-ho** [comment]
Thank you! I was able to confirm in the log files.
