### ISSUE TITLE
Hanging for >24h on "Finding pairs" step with no output

### ISSUE THREAD

**Issue by pmcarlton** [bcgsc/LongStitch#62]
Hello,

I am trying to run longstitch on an assembly and would like to know if this step normally takes a very long time, or if something may be wrong. My system is ubuntu 20.10, and I installed longstitch with conda. It completed all the tests (run_longstitch_demo.sh) without error.

I called the command with `longstitch  -d run draft=drr0-n2-g0.contigs reads=DRR424710.all_reads G=1e8` 

The contigs file is in FASTA format and 104Mb; the reads are Nanopore long reads in FASTQ format and total 7.2Gb (C. elegans genome is 100Mb in size)

For more than 24 hours the last lines of output on the terminal are:

```
Running pairing stage of ntLink ...

Parameters:
        Read minimizer files:  ['-']
        -s  drr0-n2-g0.contigs.cut250.tigmint.fa
        -m  drr0-n2-g0.contigs.cut250.tigmint.fa.k32.w100.tsv
        -p  drr0-n2-g0.contigs.cut250.tigmint.fa.k32.w100.z1000
        -n  2
        -k  32
        -a  1
        -z  1000
        -f  10
        -x  0.0
2023-02-01 15:51:00.655329 : Reading minimizers drr0-n2-g0.contigs.cut250.tigmint.fa
2023-02-01 15:51:04.726141 : Reading fasta file drr0-n2-g0.contigs.cut250.tigmint.fa
2023-02-01 15:51:04.802953 : Finding pairs
```

The file `drr0-n2-g0.contigs.cut250.tigmint.fa.k32.w100.z1000.verbose_mapping.tsv` has been created, but remains at 0 bytes.

Should I wait for a few more days/weeks or is it likely that something is hanging?
Thanks very much.

**Comment by lcoombe** [comment]
Hi @pmcarlton,

No, the ntLink step should not be taking that long on a dataset of that size. The fact that nothing has been written to that file indicates to me that it's stalled and there's an issue. 
Could you provide the full log and version of LongStitch used? I suspect there may be something wrong with LongStitch detecting the intended input reads properly at this ntLink step.

Thanks for your interest in LongStitch!
Lauren

**Comment by pmcarlton** [comment]
Thanks very much for the quick response.
I'm using longstitch v1.0.4, and the whole log is here: https://gist.github.com/pmcarlton/a05367faffba24aad3a4348e8b4582cf

The read file itself (DRR424710.all_reads.fq) seems to be fine as I could assemble it into the contigs in the first place — the log for that assembly (canu) is here in case it's needed: https://gist.github.com/pmcarlton/c686de547af0cf8e343ca6a2dfcca9ae

Thanks again!

**Comment by lcoombe** [comment]
Thanks for the log! 
So from that log, it's showing longstitch v1.0.3? We only integrated the capability to read uncompressed files in v1.0.4, so I can see that the reads file isn't being correctly passed to the ntLink stage:
```
ntLink scaffold target=drr0-n2-g0.contigs.cut250.tigmint.fa reads="" t=8 k=32 w=100 z=1000 n=2 a=1 conservative=True
```
Seeing that prompted me to double check on conda, and it looks like their bot hadn't caught the version update, so the most recent conda version is 1.0.4. I'll open a PR now to fix that!

In the meantime, you could work around that issue by cloning the github repository, and using the cloned `longstitch` driver makefile instead. If your same conda environment is activated, it should find the dependency tools for the pipeline just fine.

**Comment by pmcarlton** [comment]
That worked, thanks very much! 
I tried to run the cloned `longstitch` driver directly but it still hung; the log showed it was still trying to use `pigz` to unzip the (already-unzipped) .fq file. So I ran that line directly without `pigz`; i.e.
```
< DRR424710.all_reads.fq indexlr --long --pos --strand --len -k 32 -w 100 -t 8 - | /opt/conda/envs/syri_env/bin/share/ntlink-1.3.8-0/bin/ntlink_pair.py -p drr0-n2-g0.contigs.cut250.tigmint.fa.k32.w100.z1000 -n 2 -m drr0-n2-g0.contigs.cut250.tigmint.fa.k32.w100.tsv -s drr0-n2-g0.contigs.cut250.tigmint.fa -k 32 -a 1 -z 1000 -f 10 -x 0 --verbose -
```

when it finished with that, I re-ran the `longstitch` command using the cloned driver, and it finished in <5 minutes.

I think next time running from scratch it should finish without hangups.
Thanks again.

**Comment by lcoombe** [comment]
Great, I'm glad that it's working for you now!

I'm actually quite surprised that that command hung for you - I tested on my end on mac and linux, and running `pigz -cd` on that uncompressed file shouldn't hang (We've been running ntLink with uncompressed files for awhile). If you don't mind giving me more information, was it truly hanging (ie. no log to that verbose file, etc) for a long period of time or is it possible that the command was executing, but just took some time?

Also as a side note, LongStitch v1.0.4 is now up on conda!

**Comment by pmcarlton** [comment]
Sorry that I closed the window already and don't have the exact output; all I know is it was still waiting at the "Finding pairs…" stage  (no logging visible) but when I ran the above (indexlr directly without pigz) it finished very quickly. 

Now I'm wondering if I missed something, since the result (drr0-n2-g0.contigs.cut250.tigmint.fa.k32.w100.z1000.ntLink.scaffolds.fa) has 190 scaffolds, from an initial assembly of 107 contigs. I will try it again from scratch with conda's 1.0.4 version; thanks for putting it up there.

**Comment by lcoombe** [comment]
Thanks very much for that update! I'm glad to hear that it's working as expected with the uncompressed input. 

For the number of sequences - it's possible to have more due to the Tigmint step, which cuts the input assembly at putative misassemblies. It would be good to look at the contiguity (Ex. NG50) of the assembly at each step, which would give you a better picture of the situation. If you find that the contiguity is also lower, you could either play with a couple of Tigmint-long parameters, or skip that step and only run the ntLink scaffolding.

**Comment by pmcarlton** [comment]
thanks a lot for this last comment -- I will do as you suggest here. I'm waiting for another round of sequence data to arrive before proceeding further but I think the issue can be closed now.
