### ISSUE TITLE
Input reads in format 'reads.fastq.gz' not found

### ISSUE THREAD

**Issue by natforsdick** [bcgsc/LongStitch#69]
Although the 'Accepted read file extensions' in the documentation includes .fastq.gz, it appears the pipeline (specifically tigmint_estimate_dist.py) can't actually take the reads file with the .fastq.gz suffix. Changing the input reads file from .fastq.gz to .fq.gz resolves the issue, but I wanted to note it in case anyone else was feeling stumped by the error. 

Command line output:

> tigmint-make tigmint-long draft=01-assembly-purged reads=reads-subset cut=250 t=8 G=1300000000 span=auto dist=auto
> make[1]: Entering directory '/home/lr-scaffolding'
> /bin/share/tigmint-1.2.9-1/bin/tigmint_estimate_dist.py  -n 1000000 -o reads-subset.tigmint-long.params.tsv
> usage: tigmint_estimate_dist.py [-h] [-n N] [-p P] [-d D] [-o O] [-v] READS
> tigmint_estimate_dist.py: error: the following arguments are required: READS
> make[1]: *** [/bin/share/tigmint-1.2.9-1/bin/tigmint-make:276: reads-subset.tigmint-long.params.tsv] Error 2
> make[1]: Leaving directory '/home/lr-scaffolding'
> make: *** [/bin/share/longstitch-1.0.4-0/longstitch:213: 01-assembly-purged.cut250.tigmint.fa] Error 2

**Comment by lcoombe** [comment]
Hi @natforsdick,

Thank you very much for pointing this out! You are right - I glanced at the Tigmint makefile, and it doesn't accept `.fastq.gz` files. It looks like the other stages of LongStitch don't have this issue, luckily. 
I'll make that fix on the Tigmint side and make a new release so that it won't be an issue in the future. I'll update here when that fix is done.

Thanks for your interest in LongStitch!
Lauren

**Comment by lcoombe** [comment]
Thanks again @natforsdick - I have made this fix upstream in Tigmint v1.2.10

**Comment by scorreard** [comment]
Hi Lauren,
I ran into the same issue as Tigmint is not updated in the conda / singularity packages.
I used the work around of renaming the file, but you may want to update the packages when you / the team has time!

Thanks for the great tool,

Solenne

**Comment by lcoombe** [comment]
Hi Solenne!

Just want to double check - what version of Tigmint do you have installed in your conda env? The newest release is v1.2.10, and I did update Tigmint in conda after the new release (https://anaconda.org/bioconda/tigmint) - is it possible that an older version installed in your environment?

**Comment by scorreard** [comment]
That's interesting!
tigmint_estimate_dist.py is version 1.2.9 while longstitch is version 1.0.4

It may have been installed with quay.io rather than conda actually
On quay.io, longstitch was updated 5 months ago, which would explain why it doesn't include the latest tigmint_estimate_dist.py

```
tigmint_estimate_dist.py 1.2.9
tigmint-make tigmint-long draft=input_ont_fastq_1_assembly_consensus reads=PAG41561_pass_concat.fastq.gz cut=250 t=60 G=1.96e9 span=auto dist=auto
make[1]: Entering directory '/projects/cbp/scratch/Monterey_sea_lemon_010/V1/work/3f/2d0cd66753a2a12c2da59d37616699'
/usr/local/bin/share/tigmint-1.2.9-0/bin/tigmint_estimate_dist.py  -n 1000000 -o PAG41561_pass_concat.fastq.gz.tigmint-long.params.tsv
usage: tigmint_estimate_dist.py [-h] [-n N] [-p P] [-d D] [-o O] [-v] READS
tigmint_estimate_dist.py: error: the following arguments are required: READS
make[1]: *** [/usr/local/bin/share/tigmint-1.2.9-0/bin/tigmint-make:276: PAG41561_pass_concat.fastq.gz.tigmint-long.params.tsv] Error 2
make[1]: Leaving directory '/projects/cbp/scratch/Monterey_sea_lemon_010/V1/work/3f/2d0cd66753a2a12c2da59d37616699'
make: *** [/usr/local/bin/share/longstitch-1.0.4-0/longstitch:213: input_ont_fastq_1_assembly_consensus.cut250.tigmint.fa] Error 2
```

**Comment by lcoombe** [comment]
Hmm so the issue there may be that LongStitch and Tigmint releases are separate - since LongStitch just has Tigmint as a dependency, they are not packaged together. So if you do a fresh conda install of LongStitch, then it should install the newest version of Tigmint. 
For the quay.io images - those are static after release, so that is probably what is going on. I'll try to bump the build number of LongStitch's conda recipe so that we hopefully get an updated image on there - I'll keep you updated!

**Comment by lcoombe** [comment]
Thanks again for the heads up about Quay.io, Solenne!
The bumped build for the conda recipe has been merged, and I can see the update on Quay.io as well: https://quay.io/repository/biocontainers/longstitch?tab=tags 

Testing locally, I can see that Tigmint v1.2.10 is now installed:
```
(btl) [lcoombe@hpce706 build1]$ singularity shell longstitch_1.0.4--hdfd78af_1.sif 
Singularity> tigmint-make version
Tigmint 1.2.10
Written by Shaun Jackman @sjackman.
Singularity> 
```

**Comment by scorreard** [comment]
Thanks a lot :)
