### ISSUE TITLE
Input reads

### ISSUE THREAD

**Issue by mikeqiu00** [bcgsc/LongStitch#75]
hi
I have some questions about to input reads files. I have multiple .fastq.gz files. Do I need to merge them together when I import them？

**Comment by Keltonc** [comment]
Hi, 
I have a similar question. Is it possible to use ont and pb reads at the same time?

Thanks in advance.

**Comment by lcoombe** [comment]
Hi @Keltonc,

Yes, that should work just fine. You would just have to concatenate all of the long reads together in a single input file. 
Only one step of LongStitch (minimap2 preset for mapping in Tigmint-long) really distinguishes between long read technologies, but I don't think that using one preset over another will have a very big impact on the results. We have seen in recent tests that the presets have somewhat minimal impact on the mappings, especially with newer ONT reads.
