### ISSUE TITLE
Issues with module btllib in conda

### ISSUE THREAD

**Issue by malvaradol** [bcgsc/LongStitch#76]
Hi everyone!

I'm currently trying to run longstitch to produce scaffolds on a HiFi assembly produced with Canu, using long reads (ON). However, when I try to run the program, the following error comes up:

![image](https://github.com/bcgsc/LongStitch/assets/62664336/05e86acb-e7c4-42af-864f-731ca176a174)

All my programs are installed in a conda environment, and I have tried uninstalling and reinstalling longstitch, as well as btllib on its own, but so far nothing has worked for me.

Thanks in advance for the help with this issue.

**Comment by lcoombe** [comment]
Hi @malvaradol,

It looks like the `btllib` dependency wasn't installed properly, or there's an issue with how your environment is set up for accessing the dependency? 

To help troubleshoot, can you run the following (with your conda environment activated):
1. Confirm that you see `btllib` installed using `conda list`
2. Run `which python3`, then `python3 -c 'import btllib'` - That will just let us check that the correct python3 is being used, and then checking importing the btllib module with that python3

Thank you for your interest in LongStitch!
Lauren

**Comment by lcoombe** [comment]
Hi @malvaradol,

Hmm, it seems to be an issue with your environment when you actually launch the LongStitch jobs. 
What you're seeing when you run the commands separately indicates that btllib is properly installed.

How are you running LongStitch? Could you provide your command and the full standard out/error?

**Comment by malvaradol** [comment]
Hi Lauren,

Here's the command that I'm using to run longstitch, it is a CentOS7 HPC:

![image](https://github.com/bcgsc/LongStitch/assets/62664336/bda68bbc-e018-4eac-b1fb-4abd8317eecf)

This is the output for the stderr file:

![image](https://github.com/bcgsc/LongStitch/assets/62664336/ac730cbe-83c7-4621-9d44-8b3550b804a2)

This is the stdout output:

![image](https://github.com/bcgsc/LongStitch/assets/62664336/e865daed-93bd-46ab-817d-d72af5238210)

And I tried running the first test, this was the result that I got:

![image](https://github.com/bcgsc/LongStitch/assets/62664336/7b83e2bd-5030-44df-87ca-3efa5db2ca23)

Here's how I ran the test:

![image](https://github.com/bcgsc/LongStitch/assets/62664336/6a2ea43a-c386-4852-87b8-bed6bf66ac06)

**Comment by lcoombe** [comment]
Thanks @malvaradol - I still think it's something with the activation of your environment...
Could you add the commands that you ran on the terminal (step 2 of my first response) right before the `longstitch` command in your script, and see what you get?

**Comment by malvaradol** [comment]
Hi @lcoombe,

It seems that for now, adding `python3 -c 'import btllib'` did the trick. I will let you know if any other error comes along the way or if the jobs finishes as it should.

Thanks in advance for all the assistance :)

**Comment by malvaradol** [comment]
Hi @lcoombe,

Quick update, the program completed the run successfully. Once again, thanks for all the help and I hope that this information may be valuable for more people.

Regards,

Mateo.

**Comment by lcoombe** [comment]
Hi Mateo - thank you very much for the update! Very glad to hear that your LongStitch runs completed successfully!
