### ISSUE TITLE
Unable to run LongStitch

### ISSUE THREAD

**Issue by Oieswarya** [bcgsc/LongStitch#81]
Hello, I am trying to run LongStitch but I am constantly getting an error so I tried running the demo script and there is also am getting the error:

+ echo 'Launching LongStitch test runs...'
+ echo 'Ensure all dependencies are in your PATH'
+ echo 'Running first test - default LongStitch steps...'
+ /home/longstitch-1.0.5/longstitch -B run draft=test_scaffolds1 reads=test_reads1 G=482700 k_ntLink=24
make: command: Command not found
make: command: Command not found
make: *** No rule to make target `test_scaffolds1.fa', needed by `test_scaffolds1.cut250.tigmint.fa'.  Stop.

I have used wget to install and it is on my Linux system. Can you tell me where I am going wrong?

**Comment by lcoombe** [comment]
Hi @Oieswarya,

Did you ensure that all the dependencies are installed as well? It looks like at minimum `make` is not installed. 

If you just use `wget` to get the longstitch source code, you'll be missing many of the dependencies - they are listed here: https://github.com/bcgsc/LongStitch?tab=readme-ov-file#dependencies

For installation, we recommend using conda, as this will install all dependencies for you much more easily. Another good option is to use the quay.io longstitch docker image if you have access to docker or singularity (https://quay.io/repository/biocontainers/longstitch).

Thank you for your interest in LongStitch!
Lauren

**Comment by Oieswarya** [comment]
Thank you for the prompt reply.

I thought wget also had the dependencies. I tried to use conda but the environment was unsolvable so I used the mamba which I saw in another issue post.

It is running now. May I know if there is any way to have an output directory as currently all the outputs are getting dumped on my working directory. Also for the reads and draft do the files need to be in the working directory? For example say my draft file is draft_minia.fa and it is in a folder /home/drafts so will longstitch work if I give draft=/home/drafts/drafts_minia

**Comment by lcoombe** [comment]
Great, glad you got the install working via mamba!

If you were using wget to download the release tarball, no, it would not have dependencies - we don't package versioned dependencies within longstitch to keep things easier to maintain and more lightweight.

The reads and draft need to be in the current working directory, and the files will also be output there. If you want to use a certain (different) directory, you can create soft-links to those files in any given directory, and launch longstitch there.

**Comment by Oieswarya** [comment]
Okay! Thank you for the clarification.

longstitch is running when I am running it on the head node from the terminal bit as a slurm job it is giving me this in my .out file:make: Nothing to be done for 'run'.
EC for LongStitch:  Job completed in 0 seconds.

The .err file is empty and also there are no scaffolds getting created.


This my job script:
#!/bin/bash

#SBATCH --partition=kamiak         # Partition/Queue to use
#SBATCH --job-name=LongStich_EC           # Job name
#SBATCH --output=LongStich_EC_%j.out      # Output file (stdout)
#SBATCH --error=LongStich_EC_%j.err       # Error file (stderr)
#SBATCH --time=0-01:00:00          # Wall clock time limit Days-HH:MM:SS
#SBATCH --nodes=1                  # Number of nodes (min-max)
#SBATCH --ntasks=1                 # Number of tasks (processes)
#SBATCH --cpus-per-task=64         # Number of cores per task (threads)
#SBATCH --mem=120GB          ### Amount of memory per node

conda activate longstitch_env

# Start the timer
start_time=$(date +%s)

conda activate longstitch_env

longstitch run draft=minia_eColi reads=EC_hifi G=4499289 t=64 out_prefix=EC



# Calculate the elapsed time
end_time=$(date +%s)
elapsed_time=$((end_time - start_time))

echo "EC for LongStitch:  Job completed in $elapsed_time seconds."

**Comment by lcoombe** [comment]
Is this the first time you're running the job? What are the contents of your working directory?

Generally the message: 
```
file:make: Nothing to be done for 'run'.
```
Indicates that you have already run the tool, and the final files are already present in the current working directory (so it will not re-make these). If not, it would help to see your full log file.

**Comment by Oieswarya** [comment]
Yes you are right. There were similar named files that is why longstitch did not replicate. 
Thank you so much for all the help and such prompt replies!

**Comment by lcoombe** [comment]
You're very welcome! Good luck with your runs!
